import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider, } from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AuthenticatedLayout from "@/components/AuthLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EdTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <AuthProvider>
          <ToastContainer position="bottom-center" autoClose={5000} />
          <div className="flex min-h-screen">
            <AuthenticatedLayout>{children}</AuthenticatedLayout>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}

